import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { AxiosResponse } from 'axios'
import apiClient from '../api/apiClient'
import { ChangeEvent, useState } from 'react'

export default function Post() {
    const [title, setTitle] = useState('')
    const [content, setContent] = useState('')

    const postArticle = async () => {
        try {
            const response: AxiosResponse = await apiClient.post(
                '/api/v1/create',
                { 
                    title: title,
                    content: content,
                },
            )

            return {
                status: response.status ?? 200,
                success: true,
            }
        } catch (e: any) {
            return {
                status: e.response.status === 0 ? 500 : e.response.status,
                success: false,
            }
        }

    }

    const handleChangeTitle = (e: ChangeEvent<HTMLInputElement>) => {
        setTitle(e.target.value)
    }

    const handleChangeContent = (e: ChangeEvent<HTMLTextAreaElement>) => {
        setContent(e.target.value)
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Serverless App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <form action="/send-data-here" method="post">
                    <label htmlFor="first" className={styles.input_label}>Title:</label>
                    <input type="text" id="title" name="title" onChange={handleChangeTitle} value={title} />
                    <label htmlFor="last" className={styles.input_label}>Content:</label>
                    <textarea id="content" name="content" className={styles.content} onChange={handleChangeContent} value={content}></textarea>
                    <button type="submit" className={styles.submit_button} onClick={postArticle}>Submit</button>
                </form>
            </main>
        </div>
    )
}
